// <auto-generated />
namespace STD_Contact_Board.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedJurisdiction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedJurisdiction));
        
        string IMigrationMetadata.Id
        {
            get { return "202007011214047_SeedJurisdiction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
