namespace STD_Contact_Board.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class SeedContacts : DbMigration
    {
        public override void Up()
        {
            Sql(@"SET IDENTITY_INSERT [dbo].[Contacts] ON");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (1,N'STD Director/STD Surv Coordinator',N'Anthony Merriweather',NULL,NULL,NULL,N'Anthony.Merriweather@adph.state.al.us',NULL,NULL,1)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(2, N'HIV/STD Program Manager', N'Susan Jones', NULL, NULL, NULL, N'susan.jones@alaska.gov', NULL, NULL, 2)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (3,N'STD Program Coordinator',N'Tracy Smith',NULL,NULL,NULL,N'tracy.smith2@alaska.gov',NULL,NULL,2)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(4, N'STD Program Director', N'Rebecca Scranton', NULL, NULL, NULL, N'Rebecca.Scranton@azdhs.gov ', NULL, NULL, 3)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (5,N'STD Program Manager',N'Brandi Roberts',NULL,NULL,NULL,N'brandi.roberts@arkansas.gov',NULL,NULL,4)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(6, N'HIV/STI Epidemiologist', N'Kristyn Vang', NULL, NULL, NULL, N'Kristyn.Vang@arkansas.gov', NULL, NULL, 4)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (7,N'N/A',N'Glen Olthoff',NULL,NULL,NULL,N'Glen.Olthoff@baltimorecity.gov',NULL,NULL,5)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(8, N'N/A', N'Patrick Chaulk', NULL, NULL, NULL, N'patrick.chaulk@baltimorecity.gov', NULL, NULL, 5)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (9,N'N/A',N'Jacky Jennings',NULL,NULL,NULL,N' jjennin1@jhmi.edu',NULL,NULL,5)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(10, N'N/A', N'Christina Schumacher ', NULL, NULL, NULL, N'cschuma3@jhmi.edu', NULL, NULL, 5)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (11,N'N/A',N'Kate Leifheit ',NULL,NULL,NULL,N'kleifhe1@jhmi.edu',NULL,NULL,5)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(12, N'N/A', N'Ravikiran Muvva', NULL, NULL, NULL, N'Ravikiran.Muvva@baltimorecity.gov', NULL, NULL, 5)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (13,N'N/A',N'Hilda N. Ndirangu ',NULL,NULL,NULL,N'Hilda.Ndirangu@baltimorecity.gov',NULL,NULL,5)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(14, N'Epidemiologist/HIV Testing Project Monitor/ Surv Coordinator*', N'Sophie Sembajwe ', NULL, NULL, NULL, N'Sophie.Sembajwe@baltimorecity.gov', NULL, NULL, 5)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (15,N'N/A',N'Ryan Murphy',NULL,NULL,NULL,N'ryan.murphy@cdph.ca.gov',NULL,NULL,6)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(16, N'N/A', N'Nicole Burghardt', NULL, NULL, NULL, N'Nicole.Burghardt@cdph.ca.gov', NULL, NULL, 6)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (17,N'N/A',N'Denise Gilson ',NULL,NULL,NULL,N'Denise.Gilson@cdph.ca.gov ',NULL,NULL,6)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(18, N'STD Surveillance Coordinator', N'Irina Tabidze', NULL, NULL, NULL, N'Irina.Tabidze@cityofchicago.org', NULL, NULL, 7)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (19,N'N/A',N'Tammy Rutledge',NULL,NULL,NULL,N'tammy.rutledge@cityofchicago.org',NULL,NULL,7)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(20, N'Surveillance Program Manager', N'Anita Watkins', NULL, NULL, NULL, N'anita.watkins@state.co.us', NULL, NULL, 8)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (21,N'N/A',N'Cindy Loftin',NULL,NULL,NULL,N'cindy.loftin@state.co.us',NULL,NULL,8)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(22, N'Surveillance Coordinator', N'Mariska Osbonre-Wells', NULL, NULL, NULL, N'mariska.osborne-wells@state.co.us', NULL, NULL, 8)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (23,N'N/A',N'Adrianna Hervey  ',NULL,NULL,NULL,N'adrianna.hervey@state.co.us',NULL,NULL,8)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(24, N'N/A', N'Lynn Sosa', NULL, NULL, NULL, N'Lynn.Sosa@ct.gov', NULL, NULL, 9)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (25,N'Surveillance Manager',N'Lynn Mitchell',NULL,NULL,NULL,N' lynn.mitchell@ct.gov',NULL,NULL,9)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(26, N'N/A', N'Cathy Mosley', NULL, NULL, NULL, N'Cathy.Mosley@state.de.us', NULL, NULL, 10)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (27,N'STD Surveillance Coordinator',N'Garret Lum',NULL,NULL,NULL,N'garret.lum@dc.gov',NULL,NULL,11)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(28, N'STD Surveillance Program Manager', N'Ruth Sanon', NULL, NULL, NULL, N'Ruth.Sanon@flhealth.gov', NULL, NULL, 12)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (29,N'Epidemiologist - STD and Viral Hep Section',N'Victoria M Pearson',NULL,NULL,NULL,N'Victoria.Pearson@flhealth.gov',NULL,NULL,12)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(30, N'STD and Viral Hep Section Administrator', N'Craig Wilson', NULL, NULL, NULL, N'craig.wilson@flhealth.gov.', NULL, NULL, 12)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (31,N'STD Surveillance Manager',N'Latasha Terry',NULL,NULL,NULL,N'latasha.terry@dph.ga.gov',NULL,NULL,13)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(32, N'STD Epidemiologist', N'Liz Burkhardt', NULL, NULL, NULL, N'Elizabeth.Burkhardt@dph.ga.gov', NULL, NULL, 13)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (33,N'Epidemiologist/HIV Testing Project Monitor',N'Chisom Onyeuku ',NULL,NULL,NULL,N'chisom.onyeuku@dph.ga.gov',NULL,NULL,13)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(34, N'Surveillance lead ', N'Alan Komeya', NULL, NULL, NULL, N'Alan.Komeya@hawaii.doh.gov', NULL, NULL, 14)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (35,N'STD/HIV Epi',N'Jared Bartschi',NULL,NULL,NULL,N'BartschJ@dhw.idaho.gov',NULL,NULL,15)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(36, N'STD Prevention', N'Diana Gardner', NULL, NULL, NULL, N'gardnerd@dhw.idaho.gov', NULL, NULL, 15)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (37,N'Programs Manager',N'Aimee Shipman',NULL,NULL,NULL,N'shipmana@dhw.idaho.gov ',NULL,NULL,15)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(38, N'HIV STD and Hepatitis Programs Coordinator', N'Kimberly Matulonis-Edgar', NULL, NULL, NULL, N'Kimberly.Matulonis-Edgar@dhw.idaho.gov', NULL, NULL, 15)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (39,N'Surveillance and Evaluation Coordinator',N'Marguerite Smith',NULL,NULL,NULL,N'marguerite.smith@illinois.gov',NULL,NULL,16)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(40, N'N/A', N'Dawne Diorio', NULL, NULL, NULL, N'DDiorio@isdh.IN.gov', NULL, NULL, 17)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (41,N'N/A',N'Caitlin Conrad',NULL,NULL,NULL,N'caconrad@isdh.in.gov',NULL,NULL,17)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(42, N'STD Epidemiologist', N'Sylvia Huq', NULL, NULL, NULL, N'shuq@isdh.in.gov', NULL, NULL, 17)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (43,N'Epidemiology Coordinator (SURRG)',N'Jamie Black',NULL,NULL,NULL,N'JamBlack@isdh.IN.gov',NULL,NULL,17)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(44, N'STD Operations Manager', N'Olivia Ridgeway', NULL, NULL, NULL, N'Oridgeway@isdh.IN.gov', NULL, NULL, 17)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (45,N'STD Program Manager',N'George Walton',NULL,NULL,NULL,N'George.Walton@idph.iowa.gov ',NULL,NULL,18)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(46, N'STI/HIV Section Chief', N'Jennifer VandeVelde', NULL, NULL, NULL, N'JVandevelde@kdheks.gov', NULL, NULL, 19)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (47,N'N/A',N'Kelsey Gordon',NULL,NULL,NULL,N'KGordon@kdheks.gov',NULL,NULL,19)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(48, N'N/A', N'Stephanie Green', NULL, NULL, NULL, N'SGreen@kdheks.gov', NULL, NULL, 19)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (49,N'N/A',N'Sheri White',NULL,NULL,NULL,N'Sheri.White@ky.gov',NULL,NULL,20)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(50, N'N/A', N'Danielle Yearby', NULL, NULL, NULL, N'Danielle.Yearby@ky.gov', NULL, NULL, 20)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (51,N'N/A',N'Victoria Hubbard',NULL,NULL,NULL,N'Victoria.Hubbard@ky.gov',NULL,NULL,20)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(52, N'Surveillance Manager', N'Jessica Fridge', NULL, NULL, NULL, N'jessica.fridge@la.gov', NULL, NULL, 21)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (53,N'STD Epidemiologist Supervisor',N'Catherine Desmarais',NULL,NULL,NULL,N'catherine.desmarais@la.gov',NULL,NULL,21)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(54, N'N/A', N'', NULL, NULL, NULL, N'mgreen@ph.lacounty.gov', NULL, NULL, 22)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (55,N'Chief of HIV and STD Surveillance',N'Angela Kim',NULL,NULL,NULL,N'Akim@ph.lacounty.gov',NULL,NULL,22)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(56, N'HIV/STI Prevention Manager', N'Lauren Gauthier', NULL, NULL, NULL, N'Lauren.Gauthier@maine.gov', NULL, NULL, 23)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (57,N'Epidemiologist',N'Julie Coco',NULL,NULL,NULL,N'Julie.Coco@maine.gov',NULL,NULL,23)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(58, N'STI epidemiologist', N'Alexandra Goode', NULL, NULL, NULL, N'alexandra.goode@maryland.gov', NULL, NULL, 24)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (59,N'Deputy Chief, STI Prevention',N'Marcia Pearlowitz',NULL,NULL,NULL,N'marcia.pearlowitz@maryland.gov ',NULL,NULL,24)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(60, N'Epidemiologist ', N'Brandon Blouse', NULL, NULL, NULL, N'Brandon.Blouse@maryland.gov', NULL, NULL, 24)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (61,N'Epidemiologist and PRISM Data Manager',N'Ryan Kreisburg',NULL,NULL,NULL,N'ryan.kreisberg@maryland.gov ',NULL,NULL,24)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(62, N'Field Operations Manager', N'Christopher Borger', NULL, NULL, NULL, N'chris.borger@state.ma.us', NULL, NULL, 25)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (63,N'STD Epidemiologist ',N'Jim Kent',NULL,NULL,NULL,N'KentJ3@michigan.gov',NULL,NULL,26)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(64, N'Epidemiologist/STD Surv Coordinator', N'Khalid Bo-Subait', NULL, NULL, NULL, N'Khalid.Bo-Subait@state.mn.us', NULL, NULL, 27)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (65,N'Epidemiology and Surveillance Unit Supervisor',N'Allison LaPointe',NULL,NULL,NULL,N'allison.lapointe@state.mn.us',NULL,NULL,27)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(66, N'STD/HIV Surveillance Director', N'David Peyton', NULL, NULL, NULL, N'david.peyton@msdh.ms.gov', NULL, NULL, 28)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (67,N'STD/HIV Epidemiologist',N'Kendra Johnson',NULL,NULL,NULL,N'kendra.johnson@msdh.ms.gov',NULL,NULL,28)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(68, N'Epidemiologist/STD Surv Coordinator', N'Christie Lewis', NULL, NULL, NULL, N'christie.lewis@msdh.ms.gov', NULL, NULL, 28)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (69,N'N/A',N'Craig Highfill',NULL,NULL,NULL,N'craig.highfill@health.mo.gov',NULL,NULL,29)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(70, N'N/A', N'Angie McKee', NULL, NULL, NULL, N'angela.mckee@health.mo.gov', NULL, NULL, 29)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (71,N'',N'',NULL,NULL,NULL,N'cmurolo@mt.gov',NULL,NULL,30)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(72, N'Epidemiology Surveillance Coordinator', N'Alison Keyser-Metobo', NULL, NULL, NULL, N'Alison.keysermetobo@nebraska.gov', NULL, NULL, 31)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (73,N'STD Prevention and Partner Services Programs Manager',N'Tami Washam',NULL,NULL,NULL,N'Tami.Washam@nebraska.gov',NULL,NULL,31)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(74, N'STD and Adult VH Program Manager', N'Elizabeth Kessler', NULL, NULL, NULL, N'ekessler@health.nv.gov', NULL, NULL, 32)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (75,N'STD Surveillance Coordinator',N'Hannah Bowen',NULL,NULL,NULL,N'hannah.bowen@dhhs.nh.gov',NULL,NULL,33)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(76, N'Surveillance Epidemiology Program Manager', N'Abby Mathewson', NULL, NULL, NULL, N'Abigail.Mathewson@dhhs.state.nh.us', NULL, NULL, 33)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (77,N'Infectious Disease Surveillance Section Chief',N'Beth Daly',NULL,NULL,NULL,N'Elizabeth.R.Daly@dhhs.state.nh.us',NULL,NULL,33)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(78, N'Infectious Disease Prevention, Investigation & Care Services Section Chief', N'Lindsay Pierce', NULL, NULL, NULL, N'Lindsay.Pierce@dhhs.state.nh.us', NULL, NULL, 33)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (79,N'Surveillance Coordinator',N'Armedia Dorsey',NULL,NULL,NULL,N'armedia.dorsey@doh.state.nj.us ',NULL,NULL,34)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(80, N'Surveillance Coordinator', N'Valerie Trower', NULL, NULL, NULL, N'valerie.trower@doh.state.nj.us ', NULL, NULL, 34)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (81,N'Director, STD Services/ Surveillance Coordinator',N'Greta Anschuetz',NULL,NULL,NULL,N'Greta.Anschuetz@doh.nj.gov',NULL,NULL,34)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(82, N'STD Program Manager', N'Janine Waters', NULL, NULL, NULL, N'janine.waters@state.nm.us', NULL, NULL, 35)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (83,N'STD Surveillance Coordinator',N'Lewis Smith       ',NULL,NULL,NULL,N'lewis.smith@state.nm.us',NULL,NULL,35)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(84, N'Director, Surveillance and Field Operations', N'Robin Hennessy', NULL, NULL, NULL, N'rhenness@health.nyc.gov', NULL, NULL, 36)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (85,N'N/A',N'Julie Schillinger',NULL,NULL,NULL,N'jschilli@health.nyc.gov',NULL,NULL,36)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(86, N'City Research Scientist', N'Jennifer Slutsker', NULL, NULL, NULL, N'jsanderson@health.nyc.gov', NULL, NULL, 36)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (87,N'Surveillance Director',N'Rachel Malloy',NULL,NULL,NULL,N'Rachel.malloy@health.ny.gov',NULL,NULL,37)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(88, N'N/A', N'Alison Muse', NULL, NULL, NULL, N'alison.muse@health.ny.gov', NULL, NULL, 37)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (89,N'Surveillance Director',N'Wilson Miranda',NULL,NULL,NULL,N'wilson.miranda@health.ny.gov',NULL,NULL,37)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(90, N'Epidemiologist/STD Surv Coordinator', N'Salvatore Currenti', NULL, NULL, NULL, N'Salvatore.currenti@health.ny.gov', NULL, NULL, 37)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (91,N'N/A',N'Mara Larson',NULL,NULL,NULL,N'stateshoe@gmail.com',NULL,NULL,38)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(92, N'STD Data Quality Epidemiologist ', N'Daneille Robison', NULL, NULL, NULL, N'danielle.robinson@dhhs.nc.gov', NULL, NULL, 38)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (93,N'N/A',N'Erika Samoff',NULL,NULL,NULL,N'erika.samoff@dhhs.nc.gov',NULL,NULL,38)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(94, N'', N'Lindsey VanderBusch', NULL, NULL, NULL, N'lvanderbusch@nd.gov', NULL, NULL, 39)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (95,N'STD Program Manager',N'Debbie Merz',NULL,NULL,NULL,N'Debbie.Merz@odh.ohio.gov',NULL,NULL,40)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(96, N'Epidemiology Investigator III', N'Mary McNeill', NULL, NULL, NULL, N'mary.mcneill@odh.ohio.gov', NULL, NULL, 40)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (97,N'Administrative Program Manager',N'Terrainia Harris',NULL,NULL,NULL,N'terrainia@health.ok.gov',NULL,NULL,41)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(98, N'HIV Prevention/STD program epidemiologist', N'Irina Kasarskis', NULL, NULL, NULL, N'Irina.m.kasarskis@state.or.us', NULL, NULL, 42)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (99,N'N/A',N'Beth Butler',NULL,NULL,NULL,N'bebutler@pa.gov',NULL,NULL,43)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(100, N'N/A', N'Curt Senft', NULL, NULL, NULL, N'c-csenft@pa.gov', NULL, NULL, 43)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (101,N'Epidemiology Unit Supervisor',N'Robbie Madera',NULL,NULL,NULL,N'Robbie.Madera@Phila.Gov',NULL,NULL,44)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(102, N'STD Surveillance Manager', N'James J Williams', NULL, NULL, NULL, N'JamesJ.Williams@phila.gov', NULL, NULL, 4)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (103,N'STD Surveillance Supervisor',N'José Colón García',NULL,NULL,NULL,N'josecolon@salud.gov.pr',NULL,NULL,45)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(104, N'STD Surveillance Epidemiologist', N'Viviana Gonzalez Seda', NULL, NULL, NULL, N'viviana.gonzalez@salud.gov.pr', NULL, NULL, 45)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (105,N'HIV/STD/ Hep C/ Tb Surveillance Director',N'Sandra Miranda De León',NULL,NULL,NULL,N'smiranda@salud.gov.pr',NULL,NULL,45)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(106, N'N/A', N'Thomas Bertrand', NULL, NULL, NULL, N'thomas.bertrand@health.ri.gov', NULL, NULL, 46)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (107,N'N/A',N'Bob Kohn',NULL,NULL,NULL,N'Robert.kohn@sfdph.org',NULL,NULL,47)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(108, N'N/A', N'Trang Nguyen', NULL, NULL, NULL, N'trang.nguyen@sfdph.org', NULL, NULL, 47)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (109,N'Director, Division of Surveillance and Technical Support',N'Terri Stephens',NULL,NULL,NULL,N'stephetg@dhec.sc.gov',NULL,NULL,48)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(110, N'Surveillance Coordinator', N'Amanda Gill', NULL, NULL, NULL, N'Amanda.Gill@state.sd.us', NULL, NULL, 49)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (111,N'STD Prevention Director',N'Brad Beasley',NULL,NULL,NULL,N'brad.beasley@tn.gov',NULL,NULL,50)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(112, N'N/A', N'Parul Patel', NULL, NULL, NULL, N'Parul.Patel@tn.gov', NULL, NULL, 50)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (113,N'STD Surveillance Coordinator',N'Karen Arrowood',NULL,NULL,NULL,N'karen.arrowood@dshs.state.tx.us',NULL,NULL,51)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(114, N'STD Program Manager', N'Tammy Foskey', NULL, NULL, NULL, N'Tammy.foskey@dshs.state.tx.us', NULL, NULL, 51)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (115,N'Epidemiology Manager/STD Surv Coordinator',N'Scott White',NULL,NULL,NULL,N'swhite1@utah.gov',NULL,NULL,52)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(116, N'N/A', N'Daniel Daltry', NULL, NULL, NULL, N'daniel.daltry@state.vt.us', NULL, NULL, 53)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (117,N'STD Surveillance Coordinator',N'Kelly Bachiochi',NULL,NULL,NULL,N'kelly.bachiochi@vermont.gov',NULL,NULL,35)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(118, N'N/A', N'Jasper Lettsome', NULL, NULL, NULL, N'jasper.lettsome@doh.vi.gov', NULL, NULL, 54)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (119,N'STD Epidemiologist ',N'River Pugsley',NULL,NULL,NULL,N'river.pugsley@vdh.virginia.gov',NULL,NULL,55)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(120, N'Surveillance & Epidemiology Manager', N'Oana Vasiliu', NULL, NULL, NULL, N'oana.vasiliu@vdh.virginia.gov', NULL, NULL, 55)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (121,N'STD*MIS/Maven Data Manager',N'Raid Mohaidat',NULL,NULL,NULL,N'raid.mohaidat@vdh.virginia.gov',NULL,NULL,55)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(122, N'STD Surv Coordinator', N'Nan Haugan', NULL, NULL, NULL, N'nan.haugan@vdh.virginia.gov', NULL, NULL, 55)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (123,N'STD Surveillance Coordinator',N'Rachel Amiya',NULL,NULL,NULL,N'rachel.amiya@doh.wa.gov',NULL,NULL,56)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(124, N'STD Surveillance Coordinator', N'Debora Blankinship', NULL, NULL, NULL, N'Debora.S.Blankinship@wv.gov', NULL, NULL, 57)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (125,N'N/A',N'Anthony Wade',NULL,NULL,NULL,N'anthony.wade@dhs.wisconsin.gov',NULL,NULL,58)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(126, N'Communicable Disease Surveillance Prorgam Manager', N'Sarah Newsky', NULL, NULL, NULL, N'sarah.newsky@wyo.gov', NULL, NULL, 59)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (127,N'N/A',N'',NULL,NULL,NULL,N'farautu@yahoo.com',NULL,NULL,60)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(128, N'N/A', N'', NULL, NULL, NULL, N'johndax.moreno@gmail.com', NULL, NULL, 61)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (129,N'N/A',N'',NULL,NULL,NULL,N'mekiek@fsmhealth.fm',NULL,NULL,62)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(130, N'N/A', N'', NULL, NULL, NULL, N'Josephine.Omallan@dphss.guam.gov', NULL, NULL, 63)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (131,N'N/A',N'',NULL,NULL,NULL,N'bernadette.schumann@dphss.guam.gov',NULL,NULL,63)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(132, N'N/A', N'', NULL, NULL, NULL, N'leimattu@gmail.com', NULL, NULL, 64)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (133,N'N/A',N'',NULL,NULL,NULL,N'sibokadela@gmail.com',NULL,NULL,64)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(134, N'Public Health Epidemiology', N'Tmong Udui', NULL, NULL, NULL, N'tmong.udui@palauhealth.org', NULL, NULL, 65)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (135,N'Communicable Disease Unit Surveillance',N'Willa Wong',NULL,NULL,NULL,N'willa.wong@palauhealth.org',NULL,NULL,65)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(136, N'Communicable Disease Unit Surveillance', N'Lieb Bells', NULL, NULL, NULL, N'lieb.bells@palauhealth.org', NULL, NULL, 65)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (137,N'N/A',N'Dana Williams',NULL,NULL,NULL,N'dcropper@ncsddc.org',NULL,NULL,66)");
Sql(@"INSERT INTO[dbo].[Contacts]([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES(138, N'N/A', N'Jessica Frasure Williams', NULL, NULL, NULL, N'jfrasure-Williams@ncsddc.org', NULL, NULL, 66)");
            Sql(@"INSERT INTO [dbo].[Contacts] ([Id], [Role], [Name], [Address], [Phone], [Fax], [Email], [Hours], [Notes], [Jurisdiction_Id]) VALUES (139,N'N/A',N'William Smith',NULL,NULL,NULL,N'dharvey@ncsddc.org ',NULL,NULL,66)");
            Sql(@"SET IDENTITY_INSERT [dbo].[Contacts] OFF");

        }
        
        public override void Down()
        {
        }
    }
}
